# Generated by Django 4.2.7 on 2026-06-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sso_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
