# Generated by Django 4.2.7 on 2026-06-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_repository', '0002_user_sso_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sso_enabled',
        ),
    ]
