# Generated by Django 6.0.5 on 2026-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('OTP_GENERATED', 'OTP Generated'), ('OTP_VERIFIED', 'OTP Verified'), ('OTP_FAILED', 'OTP Failed'), ('SSO_INITIATED', 'SSO Initiated'), ('SSO_SUCCESS', 'SSO Success'), ('SSO_FAILED', 'SSO Failed'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESH', 'Token Refresh')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
